### ISSUE TITLE
☂️ Public API

### ISSUE THREAD

**Issue by sebmck** [romejs/rome#10]
The [`rome`](https://github.com/facebookexperimental/rome/tree/master/packages/rome) package will likely be the only package published for users. This will contain the CLI and a very thin API that heavily limits the public API exposed. There's no intention to publish any other packages as this would heavily restrict the changes we can make.

 - Custom project finding logic exists that matches the CLI behaviour. This is necessary due to the lack of a server #6 .
 - All exposed methods will be async. This does prevent Rome from being integrated in some tools as sync callsites are only possible, but we don't want to limit the sort of work we can do.

**Comment by baryla** [comment]
@sebmck are there any plans to get the API working in the browser? Similar to what the Rollup team is doing?

**Comment by sebmck** [comment]
@baryla Maybe, it's definitely possible. Seems like we'd want to do something like an interactive REPL. Rome deliberately doesn't use a lot of Node APIs, and the way the server is architected it allows everything to be ran in one process instead of separate worker processes, although web workers would be doable but likely unnecessary.

**Comment by baryla** [comment]
@sebmck Oh nice! I'm working on something similar but I actually utilise web workers and the speed gain is amazing compared to running all the transpilation in one process on the main thread. If Rome was opened up to allow community plugins, I can see workers in the browser environment play a massive part for speed. 

Just a side note - are you guys looking for contributors to the project? If so, it'd be nice to have a roadmap/vision or at least a list of features that still need to be implemented before `v1`. I'd love to contribute but apart from the **Philosophy** section and some potential bugs that can be worked on, there isn't much that community members can do?

**Comment by mattsjones** [comment]
The current focus is getting linting up to scratch. Starting with replicating a lot of eslints recommended rules. Checkout this issue it you wanna get involved. https://github.com/facebookexperimental/rome/issues/20

**Comment by brillout** [comment]
I'm interested in a public API from the perspective of SSR/SSG (#271).

Is there a draft somewhere online of how the public API would look like?

**Comment by KevinKelbie** [comment]
@baryla I actually have a [fork](https://github.com/KevinKelbie/rome/tree/rome-browserify) of rome which can be run in the browser which is demonstrated by with the [astexplorer for rome](https://kevinkelbie.github.io/). 

There is only one line of code I had to change to get Rome to run in the browser but the bundle output was a bit tricky so there is a [script](https://github.com/KevinKelbie/rome/blob/rome-browserify/browserify.sh) which I wrote which turns it into something the browser can understand (no doubt there is a better approach to do this within Rome itself).

**Comment by sebmck** [comment]
I don't think this is something we even want to consider at this time. I'm going to reopen if it becomes a larger concern. For linting the public API should be the LSP server which we can more thoroughly document how to communicate with.
