### ISSUE TITLE
Share Flow and TypeScript `import type` syntax

### ISSUE THREAD

**Issue by sebmck** [romejs/rome#108]
Flow supports this on import specifiers, not sure if TypeScript does so that may be the one exception to this.

**Comment by torifat** [comment]
I can pick this up 🙂

**Comment by torifat** [comment]
I haven't check the `flow` on yet but `TypeScript` one looks like this:
<img width="866" alt="Screen Shot 2020-03-03 at 9 48 24 am" src="https://user-images.githubusercontent.com/208544/75725247-280f5f00-5d34-11ea-8525-9ac06a76115e.png">

**Comment by torifat** [comment]
If `importKind = type` means import type then we don't need to do anything  https://github.com/torifat/rome/commit/ab002e30cced4d14d5efca7a330a329ceb32b7b7#diff-a710314f39f391073bdad02e8b38af51R26. Can you please have a look?

**Comment by ooflorent** [comment]
I think this issue is no longer relevant

**Comment by sebmck** [comment]
Yup.
