### ISSUE TITLE
Update js-parser tests to match babel-parser

### ISSUE THREAD

**Issue by sebmck** [romejs/rome#11]
`js-parser` is a fork of `babel-parser`. The code has diverged way too far to allow any sort of commit merging but the test fixtures are still valuable. [`packages/@romejs/js-parser/__rtests__/__rfixtures__/
`](https://github.com/facebookexperimental/rome/tree/master/packages/%40romejs/js-parser/__rtests__/__rfixtures__) should be updated with those from [`babel-parser/test/fixtures`](https://github.com/babel/babel/tree/master/packages/babel-parser/test/fixtures/) and the numerous bugs fixed that they uncover.

**Comment by pajaydev** [comment]
I would love to work on this 😊

**Comment by pajaydev** [comment]
@sebmck  Do I need to include the missing test fixtures from babel-parse ?.

**Comment by sebmck** [comment]
@pajaydev Yep. The `options.json` files will also need to be updated since they use options that Rome doesn't. Also removing any tests for syntax that Rome won't support such as some of the TC39 proposals.

**Comment by pajaydev** [comment]
@sebmck  okay cool. Thanks 👍
