### ISSUE TITLE
Questions with disallowMultipleSpacesInRegularExpressionLiterals lint rule

### ISSUE THREAD

**Issue by OriR** [romejs/rome#150]
Hey 👋 
I was looking around to get a sense of how it's built and learn from it - so far it looks pretty cool 👍 

I then looked at the linting umbrella, and that rabbit hole led me to `disallowMultipleSpacesInRegularExpressionLiterals`.

Looking at the code there, and me being a bit of a fan of regular expressions, I was interested to see this regular expression used to match multiple spaces
https://github.com/facebookexperimental/rome/blob/ee53c29ebef984ac7f86e65acfc15dd0e20502c3/packages/%40romejs/js-compiler/transforms/lint/disallowMultipleSpacesInRegularExpressionLiterals.ts#L11

Reading the linting umbrella a bit more, I saw there was a reference to the `eslint` equivalent rules and their implementations, so naturally I looked there and to my amazement I found a [different regular expression matching multiple spaces](https://github.com/eslint/eslint/blob/fd8e1f52110cada542a120750236fd1ec8779336/lib/rules/no-regex-spaces.js#L20)

Then I looked a bit more in the `eslint` source code to discover that [the complex regular expression found in rome is indeed there but in a different place](https://github.com/eslint/eslint/blob/fd8e1f52110cada542a120750236fd1ec8779336/lib/rules/no-regex-spaces.js#L91)

I started to investigate and try to figure out why there's a mismatch between these two regular expression even within `eslint` - it led me to [this comment](https://github.com/eslint/eslint/pull/8773#discussion_r123305088).
Essentially, the reason the regular expression is `/( {2,})(?: [+*{?]|[^+*{?]|$)/gu` and not simply `/( {2,})/gu` is because you don't want to match cases when the original expression is something like `/foo  +/` or `/bar  {3,4}/`, it might be because there's a significance for the first (several) space(s) but the rest can have quantifiers and the reason it's like this is because the fixer for `eslint` crashed in case there were quantifiers after (at least) the second space.
Additionally, `eslint` uses the values from the regular expression to show a more specific message about the place the error occurs, that's why it needs to separate it to two capturing groups so it'll know to report about place of the first one, not the second one.

This leads me to my first question:
Since the current code doesn't implement any kind of fixing and only checks if there are multiple spaces or not, why does this have to be the regular expression used to determine multiple spaces? at this point in time it can be simplified to `/ {2,}/`, which can also be inlined as it's shorter than most variables and is somewhat understandable on its own.

Now, this leads me to my second question/potential bug:
I don't think it works consistently due to the regular expression assigned to a variable.
Since the regular expression is placed in a variable at the file scope, it means it'll have the same reference for the entire run of the linter (correct me if I'm wrong here).
Also, regular expressions in javascript are stateful, this means that in each call to `multipleSpacesPattern.test()` the value of `multipleSpacesPattern.lastIndex` might change and upon the first match of the rule it might cause other place to not match.
You can see this live if you paste this code in your browser console:
```js
var testing = /st/gu;

console.log(testing.test('master')); // prints true
console.log(testing.lastIndex); // prints 4
console.log(testing.test('state')); // prints false
``` 

So, given two places in a code base having where you have multiple spaces in a regular expression, these occurrences of multiple spaces appear in different indices of the regular expression, the linter might only report one - it depends which regular expression it will see first.

These questions didn't come from any specific need but out of curiosity as I was looking around the code, feel free to take your time with this issue :)
If it didn't affect anyone up to this point, it will probably be a long time before someone will complain about it.

**Comment by sebmck** [comment]
These would be questions for @ikeryo1182 since they implemented the rule in #121.

**Comment by ikeryo1182** [comment]
Hi @OriR 👋
Thanks for questioning my implementing codes.

Answer for the first question:
I used that regular expression `/( {2,})(?: [+*{?]|[^+*{?]|$)/` because of referring to the implementation of eslint.
At the time, I thought the regular expression `/ {2,}/` maybe not make sure correct testing for multiple spaces, but it was my misunderstanding.
I think your thought is correct and `/( {2,})(?: [+*{?]|[^+*{?]|$)/` should be replace to `/ {2,}/` because the regular expression `/ {2,}/` is more simple and my implementing code has the lack of consideration in the below case.

- 1 space and repeatation 
```
/( {2,})(?: [+*{?]|[^+*{?]|$)/.test('[ {2}]')
=> false

/ {2,}/.test('[ {2}]')
=> false
```
- 2 spaces and repeatation 
```
/( {2,})(?: [+*{?]|[^+*{?]|$)/.test('[  {2}]')
=>false

/ {2,}/.test('[  {2}]')
=>true
```

Answer for the second question:
I think you are correct, and sorry about not knowing regular expression are stateful in javascript. 
Also, I understood the regular expression should be declared in the scope of function, class, and so on in most cases. 
In this case, it was better to declare the regular expression in the scope of not the file but the exported module.

 I larned and thought a lot by your questions. Thank you so much.

**Comment by sebmck** [comment]
I'm implementing a regex parser, so we'll be able to do this lint just based on the regex AST

**Comment by sebmck** [comment]
We now have a regex parser and it's used by the `packages/@romejs/js-compiler/lint/rules/regular/noMultipleSpacesInRegularExpressionLiterals.ts` rule so I think this can be closed out now.
