### ISSUE TITLE
Several problems with rome not working at all

### ISSUE THREAD

**Issue by vsobotka** [romejs/rome#238]
Description:

    Maybe I am trying to use rome the wrong way, I just wanted to try it out. But I am having a few problems with it. Versions:
![image](https://user-images.githubusercontent.com/4008662/78178360-cab81c00-745f-11ea-8b9e-dccc70091d2c.png)
Rome has been built from `6efc1b3a2fde5d7166ee41aa0c09e0a8aa06ed73`

## Steps To Reproduce

    Problem 1: Have a file `test.js` with a simple function and run it
![image](https://user-images.githubusercontent.com/4008662/78176519-e1a93f00-745c-11ea-82de-7fa5acf2dfc0.png)

    Problem 2: Trying to get help on the cli
![image](https://user-images.githubusercontent.com/4008662/78177037-c1c64b00-745d-11ea-9b7d-ad77000f8501.png)

     Problem 3: Hanging `rome-master` process - I would have a rome-master process running even when I have nothing with rome running elsewhere. Is that ok? I also had an incident after trying to run `rome develop` in a new cra app `npx create-react-app --template typescript`where it would fail to run with a few errors and then any rome command would just hang after `Connected to daemon` unil the `rome-master` process is killed.
     Question: Should it be possible to use rome for simple CRA generated app?

## Expected Results
     Problem 1: The same output as from node.
     Problem 2: CLI usage help.
     Problem 3: Failing with a descriptive error or something.

**Comment by ooflorent** [comment]
Thanks for trying rome!

1. `rome test` is not ready yet to be used outside of the project because `@romejs/test` is yet to be published
2. `rome --help` is currently broken. There is a WIP PR #214

**Comment by vsobotka** [comment]
@ooflorent I was running rome run, not rome test though.

**Comment by sebmck** [comment]
No commands other than `rome lint` and other project configuration commands are supported. We're currently focused on the linter/autoformatter. I'll leave this issue open so we can address them when the focus shifts to bundling, which is ultimately what `rome run` relies on.
