### ISSUE TITLE
Inner comments not attached on TSEnumDeclaration

### ISSUE THREAD

**Issue by ooflorent** [romejs/rome#380]
## Steps To Reproduce

The following file:

```ts
enum T {
  // X
}
```

produces the following AST:

```js
TSEnumDeclaration {
  id: BindingIdentifier {name: 'T'}
  const: false
  members: Array []
}
```

The inner comment is not attached to the enum declaration.

## Expected Results

The inner comment should be attached to the enum declaration.

**Comment by sebmck** [comment]
Fixed by #711
