### ISSUE TITLE
Test reporter should indicate which assertion failed

### ISSUE THREAD

**Issue by ooflorent** [romejs/rome#385]
## Steps To Reproduce

Given the following test file:

```js
import {test} from 'rome';

test(
  'dummy',
  (t) => {
    t.is(true, true);
    t.is(true, false);
    t.is(false, false);
  },
);
```

When ran, it produces the following output:

```
  ✖ t.is() failed, using Object.is semantics

     5 │   (t) => {
     6 │     t.is(true, true);
   > 7 │     t.is(true, false);
   > 8 │     t.is(false, false);
   > 9 │   },
  > 10 │ );
```

Lines 8 to 10 are also marked as error because they were not executed but it is misleading in my opinion.

## Expected Results

Only the lines covered by the assertion should be marked as error.

```
  ✖ t.is() failed, using Object.is semantics

     5 │   (t) => {
     6 │     t.is(true, true);
   > 7 │     t.is(true, false);
     8 │     t.is(false, false);
     9 │   },
    10 │ );
```

Another example:

```
  ✖ t.looksLike() failed, using prettyFormat semantics

     4 │   'dummy',
     5 │   (t) => {
   > 6 │     t.looksLike(
   > 7 │       [1, 2],
   > 8 │       [1, 2, 3],
   > 9 │     );
    10 │   },
    11 │ );
```

**Comment by sebmck** [comment]
There’s nothing deliberate about this implementation. The source maps are probably wrong, or we’re fetching the wrong call frame.

**Comment by ooflorent** [comment]
Which source maps are used? The ones from the parser or those from the formatter?

**Comment by yassere** [comment]
I wasn't able to reproduce this. Are you still seeing these errors?

**Comment by ooflorent** [comment]
Looks like it has been fixed.
