### ISSUE TITLE
Use of “AST” in Getting Started is jargon

### ISSUE THREAD

**Issue by edjw** [romejs/rome#402]
In the parse section of the Getting Started page, it says parse generates a pretty-formatted AST. I think this is jargon that isn’t understood by beginners. I’m taking this from the (great) philosophy section of the readme.

**Comment by sebmck** [comment]
Do you know of a simpler term for “pretty formatted”? The parse command is fundamentally advanced and internal so there’s certain terminology that’s just impossible to avoid.

**Comment by edjw** [comment]
I meant AST as the jargon bit! 🙂

**Comment by macovedj** [comment]
I don't think you can get very far into into parsing and compiling before encountering an AST (abstract syntax tree).  Maybe we could just put a link to an excerpt in some resource near it in the Getting Started section.  I like [this resource](https://craftinginterpreters.com/a-map-of-the-territory.html#parsing), and I guess there's always [wikipedia](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

**Comment by sebmck** [comment]
Yeah it’s impossible to avoid the term AST when we’re showing an AST. There’s no alternate terminology that would be easily understood. Once we have a finalized logo I want to redo the website and the parse command belongs in some advanced section because 99% of people will not find it useful.

**Comment by ionut-botizan** [comment]
> This command will parse a file and output a pretty formatted tree representation of the source code (also known as an [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree), or AST for short).

Would something like this be any better? The description is oversimplified and not completely accurate but experts will understand while it will also give beginners a rough idea about what the command is doing.

**Comment by aaron-simpson97** [comment]
I think the above could be a bit more helpful. You're right in that this is the kind of thing that would go in an "Advanced Topics" section, but even just for clarification and unambiguity and a link to a resource like Wikipedia for people to skim and learn more.

**Comment by sebmck** [comment]
I don't think we'll plan on even mentioning the term AST on the website so I'm going to close this out. We should definitely keep this in mind when we decide to make some of these more advanced commands public. The suggestion by @aaron-simpson97 to mark specific things as "advanced topics" and make them more separate from the rest of the docs is a great idea. Thank you @edjw for flagging this!
