### ISSUE TITLE
Running commands in contributing page after running ./scripts/build-release dist

### ISSUE THREAD

**Issue by VictorHom** [romejs/rome#404]
I followed the installation steps and then when I got to the contributing docs, I thought I could also run the commands on that page while in the cloned repo (example - `scripts/dev-rome test`) but ran into the following error below.

If I use a separate clone of the repo for the contributing instructions, there are no issues.

Just thought I would bring it in case that's not expected. It could just be a simple doc change to make users aware.

this is a neat cool project!

```
scripts/dev-rome test
```

```
packages/rome/package.json:2:11 projectManager/nameCollision 
  ✖ Duplicate package name rome

    1 │ {
  > 2 │   "name": "rome",
      │            ^^^^
    3 │   "version": "0.0.2",
    4 │   "type": "module",

  ℹ Defined already by dist/package.json
```

node - v13.0.0
mac - 10.14

**Comment by sebmck** [comment]
Where in the docs does it mention the `build-release` script? I can't find it in `CONTRIBUTING.md` or the website docs. There isn't really a reason for anyone to be running that script since `dev-rome` handles building for you, and `build-release` would only be used when we have an actual release.

**Comment by sebmck** [comment]
Actually I just noticed it's in the installation docs, which have a different flow than a contributor.
