### ISSUE TITLE
Is the Facebook CLA still a contribution requirement?

### ISSUE THREAD

**Issue by tchetwin** [romejs/rome#427]
Is this still the case:

https://github.com/romejs/rome/blob/b458829dd813b5c897f04877ba9580071c02a365/.github/CONTRIBUTING.md#L7

I notice the `facebook-github-bot` stopped adding the `CLA Signed` label ~2 days ago.

**Comment by sebmck** [comment]
It’s no longer required. We also do not need to add Facebook copyright headers to new files, however it must remain on existing ones.
