### ISSUE TITLE
a new line added in packages/@romejs/js-compiler/lint/rules/index.ts

### ISSUE THREAD

**Issue by VictorHom** [romejs/rome#434]
Description:

when you run `node scripts/lint/add.cjs testRule react`, the auto generated file ` packages/@romejs/js-compiler/lint/rules/index.ts` has a new line whereas when you run `node scripts/assert-generated`, the new line doesn't exist in `packages/@romejs/js-compiler/lint/rules/index.ts`. Just a small inconsistency that I wanted to add

## Steps To Reproduce
1. run `node scripts/lint/add.cjs testRule react`
2. git diff `packages/@romejs/js-compiler/lint/rules/index.ts`
3. note the newline
4. run `node scripts/assert-generated`
5. git diff `packages/@romejs/js-compiler/lint/rules/index.ts`
6 note no new line

## Expected Results

    Just figure they should be consistent

**Comment by sebmck** [comment]
Running `scripts/assert-generated` will format all the generated files. The other scripts deliberately don't do that as I figured people would end up running `./scripts/dev-rome lint --save` before putting up a PR anyway.
