### ISSUE TITLE
Double quotes

### ISSUE THREAD

**Issue by sebmck** [romejs/rome#442]
This issue is to discuss changing the formatting of strings to default to double instead of single quotes.

- It's much more common for an apostrophe to appear in a string than a quotation mark.
- Single quotes are used for things other than strings in other languages.
- JSON only allows double quotes.

This feels like enough reasons to justify the change.

**Comment by sebmck** [comment]
Accidentally pushed to `master` instead of another branch. Really need to setup branch protection (I've been saying this for ages...). Historically whenever I've tried to revert commits on `master` and redo them in a separate branch I've always messed up my local checkout so I'm just going to leave it as-is. 8463545ec585b49c650fcad3900e138b3e1dc9dd

**Comment by sejr** [comment]
I think it would be best to leave them as single quotes. While the frequency of apostrophes is a great point, moving to double quotes adds an extra bit of friction for _every_ (non-interpolated) string in your code.

```js
const s = 'Also, double quotes aren\'t the only way to deal with apostrophes in strings.'
```

**Comment by sebmck** [comment]
> double quotes adds an extra bit of friction for every (non-interpolated) string in your code.

What do you mean?

**Comment by sejr** [comment]
Instead of just tapping the `'` key, it becomes `Shift + '`. Considering accessibility as a motivating factor for moving from spaces to tabs, it seems like the additional key press might raise some similar concerns. No solid evidence to back to that up though.

**Comment by sebmck** [comment]
That's a good point but you're already pressing shift for other operators. The accessibility rationale for tabs is about how the code is read and processed whereas this is just a cosmetic change.

**Comment by dcleao** [comment]
Depends on your keyboard layout.

**Comment by sergiodxa** [comment]
You can always use single quotes and let Rome change them to double quotes, I do that with Prettier all the time.

**Comment by ljharb** [comment]
Apostrophes in strings are typographically incorrect; they need to be curly quotes, single or double. Using single quotes for JS strings can help catch this typographical error :-)

**Comment by Faithfinder** [comment]
There are keyboard layouts (Russian for me, sure there are others) that don't have single quotes at all (the language doesn't use apostrophes), so I've been confused by single quotes for a long time.

**Comment by akukas** [comment]
Double vs single quotes feels like mostly a matter of personal preference, or how you were "raised". I find double quotes to be more visually pleasing since they're what I've primarily used in every language since I first started coding. Consistency between languages, given JSON requires double quotes, feels like a strong argument for using them whenever convenient.

**Comment by ljharb** [comment]
Doesn’t Rome have RJSON tho, which doesn’t have that constraint?

**Comment by sebmck** [comment]
@ljharb RJSON only allows for syntax ommission and comments. It doesn't add any new data types. Property keys can be unquoted if they're a valid identifier, like in regular JS, but it still requires double quotes.

**Comment by dcleao** [comment]
@ljharb 
> Apostrophes in strings are typographically incorrect; they need to be curly quotes, single or double. Using single quotes for JS strings can help catch this typographical error :-)

1. Why aren't non-curly single quotes better than non-curly double quotes at catching this "typographical error"?
2. Why is this relevant given (what I believe is) the rarity of such content in strings?

Also, if you want to bring typography into the question, aren't double quotes de norm?

**Comment by ljharb** [comment]
@dcleao i'm saying `'` is always incorrect in prose, you want `it’s`, never `it's`.

**Comment by dcleao** [comment]
But, apart from the possible humor, do you really find that that's a strong argument for using single quotes? I usually use the reverse argument, that using double quotes is best, in one way, because it allows you to use the, so common, single quote, un-escaped. After all, most people use the "non-typographically correct" non-curly single-quote to denote the apostrophe of the possessive case.
By the way, typographically, curly or not, doubles are used preferably to singles ;-), no?

**Comment by sebmck** [comment]
Relevant to note here that we do have a list of unicode characters that look like ASCII that we use to provide syntax error hints:

![Screen Shot 2020-05-17 at 5 28 28 PM](https://user-images.githubusercontent.com/853712/82164112-db7fee00-9863-11ea-937c-857a9bdcce7f.png)

The file will even product an AST correctly with the recoverable parser (although will fatal unless we add an option to ignore parser syntax errors).

**Comment by jthegedus** [comment]
Also relevant, Prettier has an ongoing discussion for making the `singeQuote` option `true` by default - https://github.com/prettier/prettier/issues/4102 (I am a fan of double quotes)

**Comment by cascading-jox** [comment]
> Also relevant, Prettier has an ongoing discussion for making the `singeQuote` option `true` by default - [prettier/prettier#4102](https://github.com/prettier/prettier/issues/4102) (I am a fan of double quotes)

[This comment](https://github.com/prettier/prettier/issues/4102#issuecomment-378161572) in that prettier thread is the main reason why I prefer single quotes in JS. It feels unnatural to write html with two different styles depending on if it is in a .js file or .html file. 

In [this comment](https://github.com/prettier/prettier/issues/4102#issuecomment-580229613) they show evidence that it is the dominating standard in popular npm packages (seems like a good indicator 🤷‍♂️). Why go against the flow?
> * It's much more common for an apostrophe to appear in a string than a quotation mark.

I don't really buy this argument. It might be true that it is more common in a string containing a sentence to have more apostrophes but in the code I write I write way way more strings containing html/selectors with quotation marks. 
> * JSON only allows double quotes.

That is true but is that really a problem? I have never seen or written syntax correct JSON in JS.

**Comment by sebmck** [comment]
I think it's more likely that we would just skip this argument entirely and use template literals for all strings.
