### ISSUE TITLE
 node scripts/assert-generated has an indent for first line in packages/@romejs/diagnostics/categories.ts

### ISSUE THREAD

**Issue by VictorHom** [romejs/rome#455]
nothing big, but just noticed this:
<img width="773" alt="Screen Shot 2020-05-17 at 12 31 13 PM" src="https://user-images.githubusercontent.com/3211873/82154273-a7dc9e00-983a-11ea-8341-fa2630bf5fb5.png">

the task would be to just make all categories aligned

running `node scripts/lint/add.cjs aRule react` will generate the categories with the misalignment

**Comment by sebmck** [comment]
Yeah I noticed this with the tab change. Previously the indentation would have been spaces so it would have been folded in some how. @ooflorent I think this should be a relatively easy fix? I can try taking a look too.

**Comment by sebmck** [comment]
I think ignoring pendingSpaces when we have pendingTabs should be the correct fix in js-formatter Printer

**Comment by ooflorent** [comment]
Instead of pendingTabs we could have pendingIndent which would solve this.

**Comment by ooflorent** [comment]
Also another required fix is to add the pendingSpaces when adding a source position marker

**Comment by sebmck** [comment]
What would be the difference between pendingTabs and pendingIndent beyond the name?

**Comment by ooflorent** [comment]
> What would be the difference between pendingTabs and pendingIndent beyond the name?

Nothing. It better describes the intention in my opinion. Our responses collided 😅

**Comment by ooflorent** [comment]
I'll take care of the fix
