### ISSUE TITLE
vscode server crashes when rome is included in node_modules

### ISSUE THREAD

**Issue by Kelbie** [romejs/rome#476]
So currently the VSCode extension works fine if you have the following file structure:

```
├── index.js
├── package.json
└── rome.rjson
```

```
// rome.rjson
version: "^0.0.25"
```

But if you `npm install rome@^0.0.25` or `yarn add rome@^0.0.25` it crashes producing the following:

<img width="726" alt="Screenshot 2020-05-18 at 17 39 06" src="https://user-images.githubusercontent.com/19197564/82238009-7fce6700-992e-11ea-8e76-f0f198fd0529.png">

When `rome` isn't included in node_modules it seems that the vscode extension finds the development build and works fine but not so much if it finds the published npm build.

**Comment by diokey** [comment]
Is it because the server is not started automatically? What happens if you try to start the server from node_modules?

**Comment by sebmck** [comment]
@Kelbie Any idea if this is still a problem? We've done a lot of work to make the LSP more stable. Maybe @yassere has some thoughts.

**Comment by yassere** [comment]
I assume that the version you get from `npm install` is incompatible with current builds. But you should be able to run:
```
./scripts/dev-rome bundle packages/@romejs/cli/bin/rome.ts node_modules/rome/bin/rome
```
followed by
```
./scripts/run-vscode-extension .
```
and it should work fine.

**Comment by sebmck** [comment]
I'll close this out and we can come back to it once we have a stable "official" release that we can support and test.
