### ISSUE TITLE
What's the best way for a new contributor to this project to get involved?

### ISSUE THREAD

**Issue by mikesherov** [romejs/rome#48]
Congrats on Rome! A lot of people are excited about this project and some people are itching to get involved. There are already a lot of issues in the issue tracker and there are clearly laid out philosophies, etc. Seems like fertile ground for folks to contribute.

It would be great if layered on top of the good work here if there was some signal about areas you're specifically looking for active help on from people who are eager to contribute but haven't yet consumed the roadmap. Perhaps you have it already and I haven't looked closely enough. 

What is best way to get outside contributors involved? And what specifically are y'all looking for contributions to currently that aren't already assigned to the existing team?

**Comment by jcpsimmons** [comment]
It seems like this is already addressed in https://github.com/facebookexperimental/rome/issues/20 ?

**Comment by sebmck** [comment]
The team is only me currently. I'm going to be fleshing out issues over the coming weeks so the best way to be involved would be watching the repo. I'm also going to be submitting my own contributions in the form of PRs. I'll be merging them after a while by myself but would really appreciate reviews.

I've opened PR #55 with some usage instructions which detail how to use Rome more.

The status section of the README specifically calls out linting as the initial area of focus as it's relatively self contained and doesn't deal with a ton of interop with existing tools, and doesn't deal with any quirks of compilation. It's a decent target to make sure the project works with parsing, analyzing, and initializing projects. #20 is the umbrella task to track that.

**Comment by TamalAnwar** [comment]
@mikesherov You echoed my own thoughts. I am also a newbie contributor and excited to get involved in this project.

**Comment by prateekrastogi** [comment]
Excited about the past accomplishments of the author itself, I am working on same things differently at https://github.com/paxos-raft/paxos-raft

Would love to know timelines to get my hands on prod version of rome.

**Comment by sebmck** [comment]
Closing in favor of #413, #496 and #341. Please feel free to comment on any of those issues if it's something you're willing to help with. Also check out our [Discord](https://discord.gg/rome) if you have any other general questions! Thanks!

**Comment by prateekrastogi** [comment]
@sebmck  Thanks
