### ISSUE TITLE
Svelte Support?

### ISSUE THREAD

**Issue by curran** [romejs/rome#506]
Hey! I have a question about the project.

I was wondering if this is architected in such a way that you could plug in a third party transpilation step such as [Svelte](https://svelte.dev/) .

Is there any setup whereby one could author a "plugin" of sorts for Rome, similar in spirit to the [Svelte Rollup plugin](https://github.com/sveltejs/rollup-plugin-svelte), to enable Svelte?

**Comment by sebmck** [comment]
There's currently no way to have plugins. I would expect us to revisit this when we add HTML support which seems to be a prerequisite.

**Comment by mac-long** [comment]
Any news on this, it's been a couple of years and I noticed html support is coming soon. Can we confirm that Svelte support will be added? @sebmck

**Comment by ematipico** [comment]
We will open a new issue when development will start. At the moment, we don't have an HTML parser.
