### ISSUE TITLE
unescapeString doesn’t handle Unicode code point escapes

### ISSUE THREAD

**Issue by yassere** [romejs/rome#516]
Description:

The `unescapeString` function has no logic to handle Unicode code point escapes, but that's the default escape format produced by the `escapeString` function in the same package. If this mismatch is intentional, I think it should be documented.

## Steps To Reproduce

```javascript
import {escapeString, unescapeString} from "@romejs/string-escape";

const escapedRocket = escapeString("\u{1f680}");
const rocket = unescapeString(escapedRocket);
console.log(rocket)
```

## Expected Results

I expect to see a rocket. Instead, it throws an error.

**Comment by sebmck** [comment]
That package is a bit confusing. `unescapeString` is only used by the JSON parser so it follows JSON semantics. Then `escapeString` is used by the code formatter to ensure correctly escaped strings and in a bunch of other places just for pretty printing strings.

I don't think any changes need to be made to `unescapeString` but for clarity it would make sense to rename `unescapeString` to `unescapeJSONString` and `escapeString` to `escapeJSString`.

**Comment by yassere** [comment]
I can do that. I'll add a few simple tests in the same PR.
