### ISSUE TITLE
Lint rule noDuplicateCase only matches against duplicate string literals

### ISSUE THREAD

**Issue by yassere** [romejs/rome#544]
## Steps To Reproduce

Lint a file containing duplicate switch case test expressions of any type except string literal.

```
let foo = 1;
switch (foo) {
  case 1:
    break;
  case 1:
    break;
}
```

## Result

"No known problems!"

## Expected Results

The lint rule should match against duplicate numbers, identifiers, or anything else.

**Comment by sebmck** [comment]
`noDuplicateCase` currently only checks for strings. Should be straightforward to make it support numeric literals.

**Comment by yassere** [comment]
Right, I saw that. The matching ESLint rule is more universal, but if adding support for numeric literals is sufficient for our needs, this should be an easy fix.
