### ISSUE TITLE
Reorganize the `ariaHelpers.ts` file and add more test cases

### ISSUE THREAD

**Issue by ematipico** [romejs/rome#576]
At the moment `ariaHelpers.ts` is a big file that contains some type and some maps of roles/attributes.

The file is getting big and I would like to split it into separate files and try to follow the same approach or [`aria-query`](https://github.com/A11yance/aria-query/tree/master/src/etc/roles) package, although I don't it's necessary to further divide roles into abstract, literal and dpub (especially this last ones, I don't think they are needed at the moment).

As suggested by @bitpshr, we could put everything inside `rules/aria` folder. I just wonder, won't this misled other users/contributors to think that we will have aria rules inside that folder? What do you think?

Suggestions:
- move `ariaPropsMap`inside its own file
- move `roles` inside its own file
- split `roles` in different files, like `aria-query` do. That map will become very big because we will need to support more roles and add more `aria-*` props to each role
- having a file called `utilities.ts, or a folder `utility` with a file per utility. Let me know which one best suits the code style of the repository

At the time being, when I created the lint rules, I tried to implement the most used roles and covered the various combination. Although I think it's best to create more cases in order to cover almost all the roles (at least all the interactive).

The list of the roles can be found here: https://www.w3.org/TR/wai-aria-1.1/#abstract_roles (from there, downward).

May we can create a list of the interactive roles and make sure that are all covered in the lint rules?

**Comment by yassere** [comment]
Splitting up that file sounds like a great idea to me. Once #626 merges, there will be a `lint/utils` directory, and I think it would be good to model an `aria` subdirectory after the `react` subdirectory that @bitpshr created.
