### ISSUE TITLE
react/state-in-constructor redundant rule

### ISSUE THREAD

**Issue by stefanuros** [romejs/rome#599]
[state-in-constructor](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/state-in-constructor.md)
[no-direct-mutation-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-direct-mutation-state.md)

The state-in-constructor rule prevents users from initializing state anywhere except in the class constructor. This seems to already be covered by the no-direct-mutation-state rule which prevents direct state mutation everywhere but the constructor. Should this rule still be implemented for a reason that I am missing?

**Comment by ljharb** [comment]
`this.state =` is not state mutation, and that's what `state-in-constructor` prevents.

**Comment by stefanuros** [comment]
@ljharb `this.state = ` is state initialization, right? And that's the difference you're talking about? `no-direct-mutation-state` already handles cases of state initialization in places other than the constructor. Should it only handle state mutation while `state-in-constructor` handles state initialization?

**Comment by ljharb** [comment]
I can't speak for rome's implementation - the intention of `state-in-constructor` is to force people to use a public class field to initialize state, or to force them to use `this.state = {}` in the constructor. `no-direct-mutation-state` is for mutations of `this.state` itself, which does also check that `this.state` is not reassigned outside the constructor.

In other words, the rules together are complementary.
