### ISSUE TITLE
LSP server crashing on invalid syntax

### ISSUE THREAD

**Issue by yassere** [romejs/rome#618]
## Steps To Reproduce

With VS Code closed, run `./scripts/run-vscode-extension .` to start an Extension Development Host window.

Create a new file `foo.ts` and type some invalid syntax: `function {"oops"}`

## Results

LSP server crashes. From the `Rome` Output panel:

```
Fatal error occurred: DiagnosticsError: Corrupt AST
```
```
[Info  - 1:20:06 PM] Connection to server got closed. Server will restart.
```

**Comment by sebmck** [comment]
Probably need a `catchDiagnostics` somewhere in `LSPServer`.

**Comment by yassere** [comment]
I think we'd need to wrap the call to `runner.run()` in the `watchFilesFromArgs` callback and then maybe add an `onError` handler to `WatchEvents`.

Although, I'm not sure why the errors are getting that far. I'll try to figure out why they aren't being handled earlier. Ideally, syntax errors in a single file wouldn't disrupt the lint run and LSP diagnostics for any other files that changed at the same time (like when checking out a new branch).

**Comment by sebmck** [comment]
I’m pretty sure that’s it’s the auto formatting that’s causing it (the requestWorkerFormat call in LSPServer) I’m confident the linter already handles this (there’s a catchDiagnositcs somewhere in WorkerAPI#lint).

**Comment by yassere** [comment]
I saw the `catchDiagnostics` in `WorkerAPI#lint` which is why I was confused that it wasn't already handled. The server was crashing as I typed though, not when I saved, which is why I thought it was lint-related. When I have a moment later, I'll try wrapping the format call and see if that fixes it.

**Comment by yassere** [comment]
It looks like the errors are happening on `LintRunner#runGraph`

Is it reasonable to catch diagnostics in `WorkerAPI#analyzeDependencies` and return `{…UNKNOWN_ANALYZE_DEPENDENCIES_RESULT, diagnostics}` when they're caught?

**Comment by sebmck** [comment]
Yup, that should be good.
