### ISSUE TITLE
Placeholder "under construction" message on romejs.dev

### ISSUE THREAD

**Issue by sorja** [romejs/rome#628]
Description:
 `NET::ERR_CERT_COMMON_NAME_INVALID`

![image](https://user-images.githubusercontent.com/5508251/85387506-967b6580-b54d-11ea-9b3d-6f045f59f7a3.png)
![image](https://user-images.githubusercontent.com/5508251/85387538-a004cd80-b54d-11ea-9ae7-bf26fa177729.png)

## Steps To Reproduce
1. Go to https://romejs.dev/ 

## Expected Results

    See website

**Comment by sebmck** [comment]
This is intentional. We took the site down because it’s out of date and we intend to launch the new one upon the first release. This has come up often enough that I need to spend some time to redeploy a placeholder page.

**Comment by sebmck** [comment]
Done: https://romejs.dev/
