### ISSUE TITLE
Dev-rome failing to display available commands

### ISSUE THREAD

**Issue by yassere** [romejs/rome#686]
## Steps To Reproduce

Run `./scripts/dev-rome --help`

## Results

```
argv:1:11 flags/invalid ━━━━━━━━━━

  ✖ No command specified

    $ dev-rome  --help 
               ^

  ℹ To see available commands run

  $ dev-rome --help

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Requesting help for a single command like `./scripts/dev-rome check --help` still works.

**Comment by sebmck** [comment]
Oops, commandRequired shouldn’t be called by init if showHelp is true. There are test snapshots for the help output (pretty sure) and were probably updated without me actually reviewing them.

**Comment by yassere** [comment]
Ok, I'll have a PR up in a moment.

**Comment by yassere** [comment]
There wasn't a test case for the `--help` flag (the snapshot tests are just calling `parser.showHelp()` directly) and I'm having some trouble adding it. I think the `process.exit(1)` in the `shouldShowHelp` conditional is killing the test worker.

**Comment by sebmck** [comment]
Could add a new `ParserOptions` property called `noProcessExit` or something obtuse and then add an `exit` method to `Parser` that doesn't do anything when it's set.
