### ISSUE TITLE
Getting started docs appear to be incorrect

### ISSUE THREAD

**Issue by ctaylo21** [romejs/rome#713]
## Description:

  Hello! Perhaps I have missed something, but when I tried to install and use Rome, I noticed that the[ getting started instructions](https://preview.romejs.dev/docs/getting-started/) tell you to run the `rome check` command, which doesn't appear to exist. 

## Steps To Reproduce

1. `npm install rome` 
2. `rome check` (or `npx rome check`) 

## Expected Results
Check command is executed per the docs. But instead, the error `Unknown command check. Run --help to see available commands.` occurs. From looking at the `rome --help` command, it doesn't look like the `check` command even exists. 

Thanks!

**Comment by yassere** [comment]
Hi! We haven't had an official release yet, and the build on the npm registry is outdated. We recently renamed the `rome lint` command to `rome check` because we intend for it to have a broader scope than just linting. The "getting started" instructions on the preview website will be accurate once we publish a release.

**Comment by sebmck** [comment]
Might be worth adding a banner at the top of the docs to make the status more obvious.

**Comment by ctaylo21** [comment]
Ah okay, that makes sense. Thanks!

**Comment by sebmck** [comment]
Thanks for bring this up @ctaylo21! We put the domain at `preview.romejs.dev` away from `romejs.dev` to kind of hide it and show a WIP indication but it's definitely confusing. I added a banner to the website in #716 to better convey the intent. Let us know if you feel the messaging is clearer now or if you have any suggestions for improvement!
