### ISSUE TITLE
This scope does not allow `var`iables.

### ISSUE THREAD

**Issue by zinyando** [romejs/rome#88]
Description:

I get the following error when trying to bundle a `hapijs` server. 

`This scope does not allow `var`iables. This is probably because `var`iables were injected into a scope that did not contain `var` in the original source.program`

`Error occurred while requesting compile for project-quick-server/@hapi/hapi/lib/config.js`

## Steps To Reproduce

<img width="1273" alt="Screenshot 2020-03-01 at 23 10 14" src="https://user-images.githubusercontent.com/806774/75634001-51d06500-5c12-11ea-91d7-507931dff00d.png">

**Comment by sebmck** [comment]
Should be fixed by #589.
